name = "Kimi K2 Thinking"
release_date = "2025-11-08"
last_updated = "2025-12-03"
attachment = false
reasoning = true
temperature = true

tool_call = true
open_weights = true

[cost]
input = 0.45
output = 2.35

[limit]
context = 262_144
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
