name = "GPT-5-Pro"
release_date = "2025-10-06"
last_updated = "2025-10-06"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 13
output = 110

[limit]
context = 400_000
output = 128000

[modalities]
input = ["text", "image"]
output = ["text"]
