name = "GPT-4o-Aug"
release_date = "2024-11-21"
last_updated = "2024-11-21"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true

[cost]
input = 2.3
output = 9
cache_read = 1.1

[limit]
context = 128_000
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
