name = "GPT-4-Turbo"
release_date = "2023-09-13"
last_updated = "2023-09-13"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true

[cost]
input = 9
output = 27

[limit]
context = 128_000
output = 4096

[modalities]
input = ["text", "image"]
output = ["text"]
