name = "o1-pro"
release_date = "2025-03-19"
last_updated = "2025-03-19"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 140
output = 540

[limit]
context = 200_000
output = 100000

[modalities]
input = ["text", "image"]
output = ["text"]
