name = "o1"
release_date = "2024-12-18"
last_updated = "2024-12-18"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 13
output = 54

[limit]
context = 200_000
output = 100000

[modalities]
input = ["text", "image"]
output = ["text"]
