name = "o3"
release_date = "2025-04-16"
last_updated = "2025-04-16"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 1.8
output = 7.2
cache_read = 0.45

[limit]
context = 200_000
output = 100000

[modalities]
input = ["text", "image"]
output = ["text"]
