name = "Dream-Machine"
release_date = "2024-09-18"
last_updated = "2024-09-18"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true

[limit]
context = 5_000
output = 0

[modalities]
input = ["text", "image"]
output = ["video"]
