name = "DeepSeek R1 (0528)"
release_date = "2025-08-01"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true

tool_call = true
open_weights = false

[cost]
input = 0.40
output = 1.75

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
