name = "DeepSeek R1 0528 Qwen3 8B"
release_date = "2025-05-29"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-05"
tool_call = false
open_weights = true

[cost]
input = 0.02
output = 0.10

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
