name = "DeepSeek V3.2 Exp"
release_date = "2025-09-29"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true

tool_call = true
open_weights = true

[cost]
input = 0.25
output = 0.35

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
