name = "DeepSeek V3 (0324)"
release_date = "2025-08-01"
last_updated = "2025-11-08"
attachment = false
reasoning = false
temperature = true

tool_call = false
open_weights = false

[cost]
input = 0.24
output = 0.84

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
