name = "DeepSeek V3.2 Speciale"
release_date = "2025-12-01"
last_updated = "2025-12-03"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-12"
tool_call = false
open_weights = true

[cost]
input = 0.27
output = 0.41

[limit]
context = 163_840
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
