name = "Sherlock Dash Alpha"
release_date = "2025-11-15"
last_updated = "2025-11-15"
attachment = true
reasoning = false
temperature = false
tool_call = true
knowledge = "2025-11"
open_weights = false

[cost]
input = 0.00
output = 0.00

[limit]
context = 1_840_000
output = 64_000

[modalities]
input = ["text", "image"]
output = ["text"]
