name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
release_date = "2025-01-20"
last_updated = "2025-11-25"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.05
output = 0.05

[limit]
context = 33_000
output = 16_000

[modalities]
input = ["text"]
output = ["text"]