name = "moonshotai/Kimi-Dev-72B"
release_date = "2025-06-19"
last_updated = "2025-11-25"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.29
output = 1.15

[limit]
context = 131_000
output = 131_000

[modalities]
input = ["text"]
output = ["text"]