name = "Qwen/Qwen3-30B-A3B"
release_date = "2025-04-30"
last_updated = "2025-11-25"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.09
output = 0.45

[limit]
context = 131_000
output = 131_000

[modalities]
input = ["text"]
output = ["text"]