name = "Claude-Haiku-3.5-Search"
release_date = "2025-05-15"
last_updated = "2025-05-15"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true

[cost]
input = 0.68
output = 3.4
cache_read = 0.068
cache_write = 0.85

[limit]
context = 189_096
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
