name = "Claude Opus 4 Search"
release_date = "2025-06-20"
last_updated = "2025-06-20"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 13
output = 64
cache_read = 1.3
cache_write = 16

[limit]
context = 196_608
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
