name = "Claude Sonnet 3.7"
release_date = "2025-02-19"
last_updated = "2025-02-19"
attachment = true
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
open_weights = false
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 200_000
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
