name = "o3 (Preview)"
release_date = "2025-04-16"
last_updated = "2025-04-16"
attachment = true
reasoning = true
temperature = false
knowledge = "2024-05"
tool_call = true
open_weights = false
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
