name = "QwQ 32B ArliAI RpR V1"
release_date = "2025-11-08"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true

tool_call = false
open_weights = true

[cost]
input = 0.03
output = 0.11

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
