name = "GLM 4.6"
attachment = false
reasoning = false
tool_call = true
temperature = true
knowledge = "2024-04"
release_date = "2025-09-30"
last_updated = "2025-09-30"
open_weights = true

[cost]
input = 0.85
output = 2.75

[limit]
context = 202_752
output = 8_192

[modalities]
input = ["text"]
output = ["text"]