name = "DeepSeek-V3.2"
release_date = "2025-12-01"
last_updated = "2025-12-01"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-11"
tool_call = true
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 128_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
