name = "Kimi K2 Thinking"
release_date = "2025-11-06"
last_updated = "2025-11-06"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
open_weights = true

[limit]
context = 256_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]