name = "GLM 4.5 Air"
release_date = "2025-07-28"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-04"
tool_call = true
open_weights = true

[cost]
input = 0.00
output = 0.00

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
