name = "DeepSeek Reasoner"
release_date = "2025-01-20"
last_updated = "2025-09-29"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
open_weights = false

[cost]
input = 0.28
output = 0.42
cache_read = 0.028

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
