name = "Qwen2.5 VL 72B Instruct"
release_date = "2025-11-08"
last_updated = "2025-11-08"
attachment = false
reasoning = false
temperature = true

tool_call = false
open_weights = true

[cost]
input = 0.08
output = 0.33

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
