name = "MAI DS R1 FP8"
release_date = "2025-11-08"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true

tool_call = false
open_weights = true

[cost]
input = 0.30
output = 1.20

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
