name = "Gemini 2.5 Flash"
release_date = "2025-04-26"
last_updated = "2025-04-26"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 0.21
output = 1.7
cache_read = 0.052

[limit]
context = 1_065_535
output = 65_535

[modalities]
input = ["text", "image", "video", "audio"]
output = ["text"]
