name = "GPT OSS 120B"
release_date = "2025-08-05"
last_updated = "2025-11-08"
attachment = false
reasoning = true
temperature = true

tool_call = true
open_weights = true

[cost]
input = 0.04
output = 0.40

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
