name = "MiniMax M2"
release_date = "2025-10-27"
last_updated = "2025-10-27"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-10"
open_weights = false

[cost]
input = 0.3
output = 1.2

[limit]
context = 204_800
output = 128_000

[modalities]
input = ["text"]
output = ["text"]