name = "Gemma 3 27b It"
release_date = "2025-11-08"
last_updated = "2025-11-08"
attachment = false
reasoning = false
temperature = true

tool_call = true
open_weights = true

[cost]
input = 0.13
output = 0.52

[limit]
context = 96_000
output = 96_000

[modalities]
input = ["text", "image"]
output = ["text"]
