name = "Gemma 3 12b It"
release_date = "2025-11-08"
last_updated = "2025-11-08"
attachment = false
reasoning = false
temperature = true

tool_call = false
open_weights = true

[cost]
input = 0.03
output = 0.10

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text", "image"]
output = ["text"]
