# https://developers.cloudflare.com/workers-ai/models/deepseek-math-7b-instruct/

name = "@cf/deepseek-ai/deepseek-math-7b-instruct"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-02-05"
last_updated = "2024-02-06"
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 4096
output = 4096

[modalities]
input = ["text"]
output = ["text"]
