# https://developers.cloudflare.com/workers-ai/models/granite-4.0-h-micro/

name = "@cf/ibm-granite/granite-4.0-h-micro"
attachment = false
reasoning = false
tool_call = true
open_weights = false
release_date = "2025-10-07"
last_updated = "2025-12-02"
temperature = true

[limit]
context = 131000
output = 0

[cost]
input = 0.017
output = 0.11

[modalities]
input = ["text"]
output = ["text"]
