# https://developers.cloudflare.com/workers-ai/models/llama-2-7b-chat-int8/

name = "@cf/meta/llama-2-7b-chat-int8"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-09-25"
last_updated = "2023-09-25"

[cost]
input = 0.556
output = 6.667

[limit]
context = 8192
output = 8192

[modalities]
input = ["text"]
output = ["text"]
