# https://developers.cloudflare.com/workers-ai/models/llama-3.1-70b-instruct/

name = "@cf/meta/llama-3.1-70b-instruct"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-07-16"
last_updated = "2024-12-15"

[cost]
input = 0.293
output = 2.253

[limit]
context = 24000
output = 24000

[modalities]
input = ["text"]
output = ["text"]
