# https://developers.cloudflare.com/workers-ai/models/llama-guard-3-8b/

name = "@cf/meta/llama-guard-3-8b"
attachment = false
reasoning = false
tool_call = false
temperature = true
open_weights = true
release_date = "2024-07-22"
last_updated = "2024-10-11"

[cost]
input = 0.48
output = 0.03

[limit]
context = 131072
output = 0

[modalities]
input = ["text"]
output = ["text"]
