# https://developers.cloudflare.com/workers-ai/models/qwen1.5-7b-chat-awq/

name = "@cf/qwen/qwen1.5-7b-chat-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-02-03"
last_updated = "2024-04-30"
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 20000
output = 20000

[modalities]
input = ["text"]
output = ["text"]
