# https://developers.cloudflare.com/workers-ai/models/qwen3-30b-a3b-fp8/

name = "@cf/qwen/qwen3-30b-a3b-fp8"
attachment = false
reasoning = true
tool_call = true
open_weights = true
release_date = "2025-04-30"
last_updated = "2025-12-02"
temperature = true

[limit]
context = 32768
output = 0

[cost]
input = 0.051
output = 0.34

[modalities]
input = ["text"]
output = ["text"]
