# https://developers.cloudflare.com/workers-ai/models/qwen1.5-1.8b-chat/

name = "@cf/qwen/qwen1.5-1.8b-chat"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-01-30"
last_updated = "2024-04-30"
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 32000
output = 32000

[modalities]
input = ["text"]
output = ["text"]
