# https://developers.cloudflare.com/workers-ai/models/tinyllama-1.1b-chat-v1.0/

name = "@cf/tinyllama/tinyllama-1.1b-chat-v1.0"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-12-30"
last_updated = "2024-03-17"
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 2048
output = 2048

[modalities]
input = ["text"]
output = ["text"]
