# https://developers.cloudflare.com/workers-ai/models/zephyr-7b-beta-awq/

name = "@hf/thebloke/zephyr-7b-beta-awq"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2023-10-27"
last_updated = "2023-11-09"
status = "deprecated"

[cost]
input = 0
output = 0

[limit]
context = 4096
output = 4096

[modalities]
input = ["text"]
output = ["text"]
